export const FETCH_PHOTOS = 'FETCH_PHOTOS';
export const FETCH_PHOTOS_FAILED = 'FETCH_PHOTOS_FAILED';
export const FETCH_PHOTOS_SUCCESSFUL = 'FETCH_PHOTOS_SUCCESSFUL';

export const DELETE_PHOTO = 'DELETE_PHOTO';
export const DELETE_PHOTO_FAILED = 'DELETE_PHOTO_FAILED';
export const DELETE_PHOTO_SUCCESSFUL = 'DELETE_PHOTO_SUCCESSFUL';